-- PERSON
CREATE TABLE Person (
    P_ID SERIAL PRIMARY KEY,
    P_FNAME VARCHAR(50),
    P_LASTNAME VARCHAR(50),
    P_TYPE VARCHAR(1)
);

-- EMPLOYEE
CREATE TABLE Employee (
    P_ID INT PRIMARY KEY REFERENCES Person(P_ID),
    EMP_HIRE_DATE DATE,
    EMP_IS_ADM BOOLEAN,
    EMP_IS_ADV BOOLEAN
);

-- PROFESSOR
CREATE TABLE Professor (
    P_ID INT PRIMARY KEY REFERENCES Person(P_ID),
    P_OFFICE VARCHAR(10),
    P_PHONE_EXT VARCHAR(10)
);

-- SAO ADMIN
CREATE TABLE SAO_Admin (
    P_ID INT PRIMARY KEY REFERENCES Person(P_ID),
    ADM_PASSWORD VARCHAR(16)
);

-- SAO LEADER
CREATE TABLE SAO_Leader (
    P_ID INT PRIMARY KEY REFERENCES Person(P_ID),
    LDR_PASSWORD VARCHAR(16),
    ADMIN_ID INT REFERENCES SAO_Admin(P_ID)
);

-- STUDENT
CREATE TABLE Student (
    P_ID INT PRIMARY KEY REFERENCES Person(P_ID),
    STU_MAJOR VARCHAR(50),
    STU_NB_SEMESTERS INT,
    STU_IS_LDR BOOLEAN,
    STU_IS_BRD BOOLEAN
);

-- CLUB
CREATE TABLE Club (
    CLUB_ID SERIAL PRIMARY KEY,
    ADV_ID INT REFERENCES Professor(P_ID),
    CLUB_NAME TEXT,
    CLUB_TYPE TEXT,
    CLUB_FORMATION_SEM TEXT,
    CLUB_DESC TEXT
);

-- BOARD MEMBER
CREATE TABLE Board_Member (
    P_ID INT PRIMARY KEY REFERENCES Person(P_ID),
    CLUB_ID INT REFERENCES Club(CLUB_ID),
    BRD_POSITION VARCHAR(2),
    BRD_NB_SEMESTERS INT,
    BRD_PASSWORD VARCHAR(16)
);

-- EVENT
CREATE TABLE Event (
    EVENT_ID SERIAL PRIMARY KEY,
    CLUB_ID INT REFERENCES Club(CLUB_ID),
    LDR_ID INT REFERENCES SAO_Leader(P_ID),
    EVENT_NAME TEXT,
    EVENT_DESC TEXT,
    EVENT_VENUE TEXT,
    EVENT_DATE DATE,
    EVENT_START_TIME TIME,
    EVENT_END_TIME TIME
);

-- MEMBERSHIP
CREATE TABLE Membership (
    STD_ID INT REFERENCES Student(P_ID),
    CLUB_ID INT REFERENCES Club(CLUB_ID),
    MBR_STATUS BOOLEAN,
    MBR_JOIN_DATE DATE,
    PRIMARY KEY (STD_ID, CLUB_ID)
);

-- ATTENDANCE
CREATE TABLE Attendance (
    STD_ID INT REFERENCES Student(P_ID),
    EVENT_ID INT REFERENCES Event(EVENT_ID),
    PRIMARY KEY (STD_ID, EVENT_ID)
);

CREATE OR REPLACE FUNCTION update_member_status()
RETURNS TRIGGER AS $$
BEGIN
    IF (
        SELECT COUNT(DISTINCT event_id)
        FROM Attendance
        WHERE std_id = NEW.std_id
    ) >= 2 THEN
        UPDATE Member
        SET status = 'Active'
        WHERE std_id = NEW.std_id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE VIEW ActiveMembers AS
SELECT *
FROM Membership
WHERE mbr_status = true;
